version: "3.9"
services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - sow-data:/app/data/sow
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
      - VITE_SUPABASE_URL=https://tcxtdwfbifklgbvzjomn.supabase.co
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjeHRkd2ZiaWZrbGdidnpqb21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NzM0ODYsImV4cCI6MjA1MjU0OTQ4Nn0.RJbvfH3j_qMjIj8jWz1jv_cOJf2J-gMqgJdU8Q6fHoM

volumes:
  sow-data: