// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables from .env file
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://dlnoitbisrpwnmdmbrwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsbm9pdGJpc3Jwd25tZG1icnd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NjQyNjIsImV4cCI6MjA2NjE0MDI2Mn0.QBmv3RbvNxKk_OjqcYZO2UY9ZCpZ185tryBdtec7S3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);